apiVersion: v1
kind: Service
metadata:
  name: e2e-lane-enterprise
  namespace: colossus-e2e-lane-enterprise
  labels:
    app: e2e-lane-enterprise
    managed-by: colossus
spec:
  type: ClusterIP
  selector:
    app: e2e-lane-enterprise
  ports:
    - port: 80
      targetPort: 8080
